# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dynamo_pb2 as dynamo__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dynamo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DynamoServiceStub(object):
    """============================================
    Service Definitions
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/dynamo.DynamoService/Put',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/dynamo.DynamoService/Get',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetResponse.FromString,
                _registered_method=True)


class DynamoServiceServicer(object):
    """============================================
    Service Definitions
    ============================================

    """

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DynamoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.DynamoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.DynamoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DynamoService(object):
    """============================================
    Service Definitions
    ============================================

    """

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/Put',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.DynamoService/Get',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/dynamo.NodeService/Join',
                request_serializer=dynamo__pb2.JoinRequest.SerializeToString,
                response_deserializer=dynamo__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.ReplicateGet = channel.unary_unary(
                '/dynamo.NodeService/ReplicateGet',
                request_serializer=dynamo__pb2.ReplicateGetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.ReplicateGetResponse.FromString,
                _registered_method=True)
        self.ReplicatePut = channel.unary_unary(
                '/dynamo.NodeService/ReplicatePut',
                request_serializer=dynamo__pb2.ReplicatePutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.ReplicatePutResponse.FromString,
                _registered_method=True)
        self.CoordinatePut = channel.unary_unary(
                '/dynamo.NodeService/CoordinatePut',
                request_serializer=dynamo__pb2.PutRequest.SerializeToString,
                response_deserializer=dynamo__pb2.PutResponse.FromString,
                _registered_method=True)
        self.CoordinateGet = channel.unary_unary(
                '/dynamo.NodeService/CoordinateGet',
                request_serializer=dynamo__pb2.GetRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetResponse.FromString,
                _registered_method=True)
        self.ReceiveHint = channel.unary_unary(
                '/dynamo.NodeService/ReceiveHint',
                request_serializer=dynamo__pb2.HintedHandoff.SerializeToString,
                response_deserializer=dynamo__pb2.HintResponse.FromString,
                _registered_method=True)
        self.Gossip = channel.unary_unary(
                '/dynamo.NodeService/Gossip',
                request_serializer=dynamo__pb2.GossipPing.SerializeToString,
                response_deserializer=dynamo__pb2.GossipPong.FromString,
                _registered_method=True)
        self.GetCluster = channel.unary_unary(
                '/dynamo.NodeService/GetCluster',
                request_serializer=dynamo__pb2.GetClusterRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetClusterResponse.FromString,
                _registered_method=True)
        self.GetAllKeys = channel.unary_unary(
                '/dynamo.NodeService/GetAllKeys',
                request_serializer=dynamo__pb2.GetAllKeysRequest.SerializeToString,
                response_deserializer=dynamo__pb2.GetAllKeysResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Join(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicatePut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoordinatePut(self, request, context):
        """Coordinator forwarding
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CoordinateGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveHint(self, request, context):
        """Hinted handoff
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Gossip(self, request, context):
        """Gossip protocol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCluster(self, request, context):
        """Cluster discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllKeys(self, request, context):
        """Anti-entropy (Merkle tree sync)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=dynamo__pb2.JoinRequest.FromString,
                    response_serializer=dynamo__pb2.JoinResponse.SerializeToString,
            ),
            'ReplicateGet': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateGet,
                    request_deserializer=dynamo__pb2.ReplicateGetRequest.FromString,
                    response_serializer=dynamo__pb2.ReplicateGetResponse.SerializeToString,
            ),
            'ReplicatePut': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicatePut,
                    request_deserializer=dynamo__pb2.ReplicatePutRequest.FromString,
                    response_serializer=dynamo__pb2.ReplicatePutResponse.SerializeToString,
            ),
            'CoordinatePut': grpc.unary_unary_rpc_method_handler(
                    servicer.CoordinatePut,
                    request_deserializer=dynamo__pb2.PutRequest.FromString,
                    response_serializer=dynamo__pb2.PutResponse.SerializeToString,
            ),
            'CoordinateGet': grpc.unary_unary_rpc_method_handler(
                    servicer.CoordinateGet,
                    request_deserializer=dynamo__pb2.GetRequest.FromString,
                    response_serializer=dynamo__pb2.GetResponse.SerializeToString,
            ),
            'ReceiveHint': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveHint,
                    request_deserializer=dynamo__pb2.HintedHandoff.FromString,
                    response_serializer=dynamo__pb2.HintResponse.SerializeToString,
            ),
            'Gossip': grpc.unary_unary_rpc_method_handler(
                    servicer.Gossip,
                    request_deserializer=dynamo__pb2.GossipPing.FromString,
                    response_serializer=dynamo__pb2.GossipPong.SerializeToString,
            ),
            'GetCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCluster,
                    request_deserializer=dynamo__pb2.GetClusterRequest.FromString,
                    response_serializer=dynamo__pb2.GetClusterResponse.SerializeToString,
            ),
            'GetAllKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllKeys,
                    request_deserializer=dynamo__pb2.GetAllKeysRequest.FromString,
                    response_serializer=dynamo__pb2.GetAllKeysResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dynamo.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dynamo.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/Join',
            dynamo__pb2.JoinRequest.SerializeToString,
            dynamo__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/ReplicateGet',
            dynamo__pb2.ReplicateGetRequest.SerializeToString,
            dynamo__pb2.ReplicateGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicatePut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/ReplicatePut',
            dynamo__pb2.ReplicatePutRequest.SerializeToString,
            dynamo__pb2.ReplicatePutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CoordinatePut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/CoordinatePut',
            dynamo__pb2.PutRequest.SerializeToString,
            dynamo__pb2.PutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CoordinateGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/CoordinateGet',
            dynamo__pb2.GetRequest.SerializeToString,
            dynamo__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveHint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/ReceiveHint',
            dynamo__pb2.HintedHandoff.SerializeToString,
            dynamo__pb2.HintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Gossip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/Gossip',
            dynamo__pb2.GossipPing.SerializeToString,
            dynamo__pb2.GossipPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/GetCluster',
            dynamo__pb2.GetClusterRequest.SerializeToString,
            dynamo__pb2.GetClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dynamo.NodeService/GetAllKeys',
            dynamo__pb2.GetAllKeysRequest.SerializeToString,
            dynamo__pb2.GetAllKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
